## yaml file for travis
language: python
python:
  - "3.8"
# command to install dependencies
install:
  pip install requests pyyaml pytest pytest-cov
  pip install qiskit
# command to run tests
script:
    - pytest --cov
# need to change directory before building docs
    - cd docs
    - sphinx-build . build/html
    - touch docs/build/html/.nojekyll
    - cd ..
deploy:
  - provider: pages:git
    skip_cleanup: true
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true